// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./components/form/FormInput copy.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Footer: typeof import('./components/Footer.vue')['default']
    FormCheckbox: typeof import('./components/form/FormCheckbox.vue')['default']
    FormDatepicker: typeof import('./components/form/FormDatepicker.vue')['default']
    FormInput: typeof import('./components/form/FormInput.vue')['default']
    FormItem: typeof import('./components/form/FormItem.vue')['default']
    FormItems: typeof import('./components/form/FormItems.vue')['default']
    FormRadio: typeof import('./components/form/FormRadio.vue')['default']
    FormSelect: typeof import('./components/form/FormSelect.vue')['default']
    LptCol: typeof import('./components/layout/LptCol.vue')['default']
    LptRow: typeof import('./components/layout/LptRow.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
